### ISSUE TITLE
Byte array

### ISSUE THREAD

**Issue by 2020testuser** [cloudevents/sdk-python#132]
Hi,
This is not a bug. However, sort of question and need clarification.
Could anyone please clarify on the below?

1. What is the best way to get the avro message data (got from kafka) from CloudEvent request body which is a byte array format?

2. For avro, since the schema id is part of the message itself, is there any method available to get the schema id? 
3. For the dynamic schema, are there functions available in sdk-python to get the message by fetching the schema dynamically based on the schema id from the registry?
Thanks!

**Comment by grant** [comment]
Hey there,

This SDK mostly uses HTTP, and doesn't have support for Avro. This SDK is mostly used for HTTP requests and responses. There's no dynamic schema functionality afaik.

Since this issue is old, I'm going to close it. However, if you feel like it should be opened, lmk!

You might get more of an answer with the CE call or making an issue in the spec repo:

https://github.com/cloudevents/spec

–Grant
