### ISSUE TITLE
pypi_packaging.py in MANIFEST

### ISSUE THREAD

**Issue by krishanj20** [cloudevents/sdk-python#133]
Hi, I want to be able to build this into a conda repository, but i need pypi_packaging.py in your MANIFEST and rebuild. This would allow me to create a conda package.

**Comment by grant** [comment]
Hi there,

I'm not sure exactly what this is, but I believe this module doesn't require a `MANIFEST.in` file.

If you're suggesting we include one, can you be more specific with details? A PR would be great.

**Comment by di** [comment]
The issue is that we're calling functions in `setup.py` that we don't include in our distribution, so downstream consumers can't build this.

Instead of adding `pypi_packaging.py` to our distribution (which doesn't need to be redistributed as it's just used for releasing this project to PyPI) I moved the relevant functions into `setup.py` instead: #151.
