### ISSUE TITLE
CloudEvent class needs better access to cloudevent fields

### ISSUE THREAD

**Issue by cumason123** [cloudevents/sdk-python#49]
## Expected Behavior
```python
event = CloudEvent(headers, data)
event.specversion
```

## Actual Behavior
```python
event = CloudEvent(headers, data)
event['specversion']
```

## Steps to Reproduce the Problem
```python
from cloudevents.sdk import converters
from cloudevents.sdk.http_events import CloudEvent
import requests


attributes = {
    "Content-Type": "application/json",
    "type": "README.sample.binary",
    "id": "binary-event",
    "source": "README",
}
data = {"message": "Hello World!"}

event = CloudEvent(attributes, data)
event['specversion']
```

**Comment by evankanderson** [comment]
I'm not sure that you want attribute accessors, given that the set of CE attributes are unknown a priori due to the possible presence of extensions. Using attribute access may also make iterating over all the attributes, or adding additional methods on the class more difficult.

**Comment by cumason123** [comment]
That seems reasonable. Perhaps in the future we change the module naming schema to actually use the internal event python properties simply because the current getitem overload isn't very verbose although that can be a problem for another day. 

Regardless we should document in the README attribute field access via the existing getitem mapping because consumers will definitely want to know how to read properties about a given event.

I'll follow up with a PR on a README overhaul. I'm thinking about further deprecating the base event class instantiations from the README as that's not the preferred way to create cloudevents atm. Thoughts @evankanderson?

**Comment by evankanderson** [comment]
All the old base stuff needs to disappear or at least be hidden and not recommended for external use. You'll note that I didn't hold on to the base event in `http_events.py` after parsing. I just wasn't quite ready to bite the bullet of restructuring all the parsing code.

One thing I would try to do before declaring a `v1` API would be to also separate out the HTTP components from the event class. At the very least, I'd hope to have the following to/from static (non-class) methods:

* `to_json` - converts to transport-agnostic JSON (for example, if you want to store in a file)
* `to_structured_http` - probably the equivalent of `.to_http(converters.TypeStructured)`
* `to_binary_http` - ditto for `.to_http(converters.TypeBinary)`
* `from_json` - converts to and from transport-agnostic JSON
* `from_http` - handles both structured and binary HTTP; structured will be easy with `from_json`

**Comment by evankanderson** [comment]
I'm -1 on having a sub-attribute named `event` on a CloudEvent. `attribute` would be slightly better, but I don't think nested objects is the way to go.

If we want to do attribute access, they should just be top-level properties, since the name `data` is (or should be) treated as reserved from an extension PoV -- it would break JSON encoding to try to add a `data` extension).

If you do want to be able to use attribute access instead of map-style access, I think the following should be sufficient:

* Implement `__getattr__` and `__setattr__`, probably [as described in this StackOverflow post](https://stackoverflow.com/a/16237698/1543502).

* Figure out how you want to handle iterating over the attributes (special method?). Since [CloudEvents requires that all attributes be named following`[a-z0-9]{,20}`](https://github.com/cloudevents/spec/blob/v1.0/spec.md#attribute-naming-convention), including an `_` in the method name should be enough to avoid a collision. Sadly, you may also discover that it's hard to handle an attribute like `2cool4school` or `1`, so we probably need the `__getitem__` version as well.

**Comment by evankanderson** [comment]
The point on autocomplete is interesting -- I haven't looked much at how to hint that in various editors.

**Comment by cumason123** [comment]
I'm also -1 on the event name also hence me saying the naming schema I gave above sounds inconvenient. Top level properties rather than nested objects is definitely preferable although marginally more annoying to implement. I further agree we should keep the getitem overload regardless.

The [a-z0-9] naming schema is an interesting point I was unaware of. I would like to know why the spec permits this anyways, although there are no existing attributes where the first character is a number that I know of. 

I also agree the http function handles you described should be separate from the event itself. Perhaps we should break this issue up until several smaller issues.

**Comment by matejvasek** [comment]
What about just adding `properties` for the six known attributes (id,type,specversion,source,time,subject)?
I really like dot access more because of IDE completion and type hinting.

See: https://github.com/cloudevents/sdk-python/blob/4030c61368889fb8301de2bb60eae0f381915809/cloudevents/http/event.py

**Comment by matejvasek** [comment]
Also Java or Go sdk allow dot access on the known attributes.
